server:
  port: 8070

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/api/notifications/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 