spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
  datasource:
    url: jdbc:postgresql://postgres-notifications:5432/notifications
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql

server:
  port: 8083 