server:
  port: 8070

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service-graphql
          uri: http://product-service:8081
          predicates:
            - Path=/graphql/products
          filters:
            - RewritePath=/graphql/products, /graphql
        - id: order-service-graphql
          uri: http://order-service:8082
          predicates:
            - Path=/graphql/orders
          filters:
            - RewritePath=/graphql/orders, /graphql
        - id: notification-service-graphql
          uri: http://notification-service:8083
          predicates:
            - Path=/graphql/notifications
          filters:
            - RewritePath=/graphql/notifications, /graphql
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics 